/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStaffIndexRouteImport } from './routes/_layout/staff/index'
import { Route as LayoutNewsIndexRouteImport } from './routes/_layout/news/index'
import { Route as LayoutGalleryIndexRouteImport } from './routes/_layout/gallery/index'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutContactIndexRouteImport } from './routes/_layout/contact/index'
import { Route as LayoutClubsIndexRouteImport } from './routes/_layout/clubs/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStaffIndexRoute = LayoutStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNewsIndexRoute = LayoutNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGalleryIndexRoute = LayoutGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactIndexRoute = LayoutContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClubsIndexRoute = LayoutClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutIndexRoute
  '/clubs': typeof LayoutClubsIndexRoute
  '/contact': typeof LayoutContactIndexRoute
  '/events': typeof LayoutEventsIndexRoute
  '/gallery': typeof LayoutGalleryIndexRoute
  '/news': typeof LayoutNewsIndexRoute
  '/staff': typeof LayoutStaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutIndexRoute
  '/clubs': typeof LayoutClubsIndexRoute
  '/contact': typeof LayoutContactIndexRoute
  '/events': typeof LayoutEventsIndexRoute
  '/gallery': typeof LayoutGalleryIndexRoute
  '/news': typeof LayoutNewsIndexRoute
  '/staff': typeof LayoutStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/clubs/': typeof LayoutClubsIndexRoute
  '/_layout/contact/': typeof LayoutContactIndexRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
  '/_layout/gallery/': typeof LayoutGalleryIndexRoute
  '/_layout/news/': typeof LayoutNewsIndexRoute
  '/_layout/staff/': typeof LayoutStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/clubs'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/clubs'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/news'
    | '/staff'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/about/'
    | '/_layout/clubs/'
    | '/_layout/contact/'
    | '/_layout/events/'
    | '/_layout/gallery/'
    | '/_layout/news/'
    | '/_layout/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/staff/': {
      id: '/_layout/staff/'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof LayoutStaffIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/news/': {
      id: '/_layout/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof LayoutNewsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gallery/': {
      id: '/_layout/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof LayoutGalleryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact/': {
      id: '/_layout/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clubs/': {
      id: '/_layout/clubs/'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof LayoutClubsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutClubsIndexRoute: typeof LayoutClubsIndexRoute
  LayoutContactIndexRoute: typeof LayoutContactIndexRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
  LayoutGalleryIndexRoute: typeof LayoutGalleryIndexRoute
  LayoutNewsIndexRoute: typeof LayoutNewsIndexRoute
  LayoutStaffIndexRoute: typeof LayoutStaffIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutClubsIndexRoute: LayoutClubsIndexRoute,
  LayoutContactIndexRoute: LayoutContactIndexRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
  LayoutGalleryIndexRoute: LayoutGalleryIndexRoute,
  LayoutNewsIndexRoute: LayoutNewsIndexRoute,
  LayoutStaffIndexRoute: LayoutStaffIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
